name: Bump Version

on:
  push:
    branches: ["dev"]

env:
  GITHUB_EVENT_NAME: ${{ github.event_name }}
  SHOULD_DEPLOY: ${{ false }}

jobs:
  bump_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: version_check
        id: version_check
        run: |
          echo "Hello, ${{ github.actor }}!"
          LATEST_VERSION=$(git tag -l | sort -V | tail -n 1 || echo "0.0.0")
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: bump_version
        id: bump_version
        run: |
          echo "Hello, ${{ github.actor }}!"          
          echo "Current Version: ${{ steps.version_check.outputs.LATEST_VERSION }}"

          # 현재 버전을 파싱
          CURRENT_VERSION="${{ steps.version_check.outputs.LATEST_VERSION }}"

          # 메이저, 마이너, 패치 버전 추출
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

          # 패치 버전 1 증가
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"

          echo "New Version: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT

          # Git 설정
          git config --local user.email "pam9411@naver.com"
          git config --local user.name "Seongseokwon"

          # 새 태그 생성
          git tag "$NEW_VERSION"
          git push origin "$NEW_VERSION"

          echo "Version bumped from $CURRENT_VERSION to $NEW_VERSION"
