name: Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: |
          [필수] 배포할 환경 선택(main, dev)
        required: true
        default: dev
        type: choice
        options:
          - main
          - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Repository
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.inputs.branch}}
      - name: Echo 브랜치 이름
        run: |
          echo "현재 빌드 브랜치: ${{github.event.inputs.branch}}"
          current_branch=${{github.event.inputs.branch}}
          echo "current_branch=$current_branch" >> $GITHUB_OUTPUT

      - name: 환경설정
        run: |
          echo "현재 빌드 브랜치: $current_branch"
