name: Hello CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: ["closed"]

env:
  GITHUB_EVENT_NAME: ${{ github.event_name }}
  GITHUB_PULL_REQUEST_MERGED: ${{ github.event.pull_request.merged }}
  SHOULD_DEPLOY: ${{ false }}

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello, ${{ github.actor }}!"
          echo "Current Ref, ${{github.ref}}"
          if [ "${GITHUB_EVENT_NAME}" = "pull_request" ] && [ "${GITHUB_PULL_REQUEST_MERGED}" = "true" ]; then
              echo "This is a pull request and it has been merged"
              echo "should_deploy=true" >> $GITHUB_ENV
              echo "Deploy State updated"
          else
              echo "This is not a pull request"
              echo "should_deploy=false" >> $GITHUB_ENV
          fi
