name: Hello CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Print greeting
              run: |
                echo "Hello, ${{ github.actor }}!"
                if [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
                    echo "This is a pull request"
                else
                    echo "This is not a pull request"
                fi
              env:
                GITHUB_EVENT_NAME: ${{ github.event_name }}