name: Hello CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [closed]

jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Print greeting
              run: |
                echo "Hello, ${{ github.actor }}!"
                if [ "${GITHUB_EVENT_NAME}" = "pull_request" ] && [ "${GITHUB_PULL_REQUEST_MERGED}" = "true" ]; then
                    echo "This is a pull request and it has been merged"
                    echo "Deploy State updated" >> $GITHUB_OUTPUT
                else
                    echo "This is not a pull request"
                fi
              env:
                GITHUB_EVENT_NAME: ${{ github.event_name }}
                GITHUB_PULL_REQUEST_MERGED: ${{ github.event.pull_request.merged }}
